# Generated by Django 5.2.3 on 2025-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealpreference',
            name='calories_per_day',
        ),
        migrations.RemoveField(
            model_name='mealpreference',
            name='goal',
        ),
        migrations.AlterField(
            model_name='mealpreference',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mealpreference',
            name='diet_type',
            field=models.CharField(default='veg', max_length=20),
        ),
        migrations.AlterField(
            model_name='mealpreference',
            name='location',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealpreference',
            name='meals_per_day',
            field=models.IntegerField(choices=[(3, '3 meals/day'), (5, '5 meals/day')], default=3),
        ),
    ]
