# Generated by Django 5.2.3 on 2025-07-01 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_goal', models.PositiveIntegerField(default=10000)),
                ('calorie_goal', models.PositiveIntegerField(default=2000)),
                ('water_goal', models.FloatField(default=2.5)),
                ('sleep_goal', models.FloatField(default=8.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
