# Generated by Django 5.2.3 on 2025-06-24 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailystat',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
