# Generated by Django 5.2.3 on 2025-06-24 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_userdailystat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailystat',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
